### ISSUE TITLE
Live link not working

### ISSUE THREAD

**Issue by nickmackenzie** [jermzblake/projectWolverine#84]
Hey do you guys have the env variables for the DB so we can get this up on another hosting platform? Heroku shut down their free teir. @nickmackenzie @conspop @jermzblake

**Comment by jermzblake** [comment]
I don't see any on my end. I believe @conspop set up the deployment so hopefully, he can shed some light. The world needs Trivia-Night.  @conspop if you go to your heroku dashboard, click on the project, then click on settings in the top nav. Finally you will see a button, **Reveal config vars**. Click on this and you'll have your variables.

**Comment by nickmackenzie** [comment]
We need our baby to live! BTW Im in the process of transferring all my other projects from Heroku because nothing is working. RIP

**Comment by jermzblake** [comment]
Yeah migrating my other projects will be my task this weekend. What alternative are you using?

**Comment by nickmackenzie** [comment]
Its a task for sure, I'm using [Render](https://render.com/). Free tier seems to fit the bill and its like the heroku interface

**Comment by conspop** [comment]
How you doin Nick? Jermaine and I have been meeting for beers every once in a while. Would love to catch up some time if you're able to make it into the big smoke!

**Comment by nickmackenzie** [comment]
All good man. Hope you guys are well. I will for sure hit you guys up if I'm up there! Would love to meet you guys IRL.

Just gonna delete your comment @conspop so the secrets stay secret, I think this is a public repo.

**Comment by jermzblake** [comment]
Thanks Seb. I've removed the secrets since this is a public repo. Have either of you, @conspop or @nickmackenzie redeployed the app yet? If not, I can. Just don't see the need to do it if already up.

**Comment by nickmackenzie** [comment]
Not yet @jermzblake
